trigger:
  branches:
    include:
      - master
      - feature/*
      - release/*
      - refs/tags/*
pr:
  autoCancel: true
  branches:
    include:
      - master

resources:
  repositories:
    - repository: rsg
      type: github
      name: RocketSurgeonsGuild/AzureDevopsTemplates
      ref: refs/tags/v0.10.5
      endpoint: github

variables:
  - group: rsg-bot
  - name: CONFIGURATION
    value: Release
  - name: VERBOSITY
    value: Normal
  - name: COVERAGE
    value: "$(Agent.BuildDirectory)/c"
  - name: ARTIFACTS
    value: $(Build.ArtifactStagingDirectory)
  - name: DOTNET_SKIP_FIRST_TIME_EXPERIENCE
    value: "true"
  - name: CodeCovToken
    value: 'abd8cf66-21fa-45eb-b45e-35a3022a7402'

jobs:
  - job: GitVersion
    pool:
      vmImage: "windows-2019"
    steps:
      - template: gitversion/store.yml@rsg
        parameters:
          NuGetVersion: "5.2.0"

  - template: pipeline/nuke-job.yml@rsg
    parameters:
      name: 'Build'
      dependsOn: GitVersion
      Configuration: $(Configuration)
      Verbosity: $(Verbosity)
      GitHub: true
      GitHubPackages: false
      DotNetVersion: "2.2.300"
      DotNet3Version: "3.0.100"
      NuGetVersion: "5.2.0"
      EnableReleaseNotes: false
      
  - job: Publish
    pool:
      vmImage: "windows-2019"
    dependsOn:
      - Build
    steps:
      - task: DownloadBuildArtifacts@0
        displayName: "Download NuGet Packages"
        inputs:
          specificBuildWithTriggering: true
          downloadType: single
          artifactName: 'Nupkg - Windows'
          downloadPath: $(Build.ArtifactStagingDirectory)/nuget/
      - template: standard/nuget-push.yml@rsg
        parameters:
          Artifacts: "$(Build.ArtifactStagingDirectory)/"
          NuGetVersion: "5.2.0"
          Verbosity: $(Verbosity)
          GitHubPackages: false