trigger:
  batch: true
  branches:
    include:
      - master
      - feature/*
      - release/*
      - refs/tags/*
  paths:
    exclude:
      - '**/*.md'
      - '.appveyor.yml'
      - '.codecov.yml'
      - 'GitVersion.yml'
      - 'GitReleaseManager.yaml'
      - .vscode/*
      - .git*
      - .editorconfig
      - .nuke
      - LICENSE

pr:
  autoCancel: true
  branches:
    include:
      - master

resources:
  repositories:
    - repository: rsg
      type: github
      name: RocketSurgeonsGuild/AzureDevopsTemplates
      ref: refs/tags/v0.12.0
      endpoint: github

variables:
  - name: CONFIGURATION
    value: Release
  - name: VERBOSITY
    value: Normal
  - name: COVERAGE
    value: '$(Agent.BuildDirectory)/c'
  - name: ARTIFACTS
    value: $(Build.ArtifactStagingDirectory)
  - name: DOTNET_SKIP_FIRST_TIME_EXPERIENCE
    value: 'true'
  - name: CodeCovToken
    value: 'abd8cf66-21fa-45eb-b45e-35a3022a7402'
  - group: rsg-bot

  # Fixes the github package repo warnings on restore
  - name: EmitAssetsLogMessages
    value: false
  - name: HideWarningsAndErrors
    value: true

jobs:
  - template: jobs/gitversion.yml@rsg
  - template: jobs/publish-release.yml@rsg
    parameters:
      EnableReleaseNotes: false
      GitHub: true
      GitHubPackages: true
      GitHubAuthVariableGroup: rsg-bot
      PublishNuGetPackagesFromArtifact: 'NuGet - macOS'
      AuthNuGetFeeds:
        - name: RocketSurgeonsGuild
          source: https://nuget.pkg.github.com/RocketSurgeonsGuild/index.json
          username: $(GitHub.UserName)
          password: $(GitHub.Token)

  - job: Build
    dependsOn:
      - ${{ if startsWith(variables['Build.SourceBranch'], 'refs/tags/v') }}:
          - GitHub_Draft_Release
    variables:
      - group: rsg-bot
    strategy:
      matrix:
        macOS:
          BuildName: 'macOS'
          ImageName: 'macOS-latest'
    pool:
      vmImage: $(ImageName)
    steps:
      - template: support/mono.yml@rsg
      - ${{ if startsWith(variables['Build.SourceBranch'], 'refs/tags/v') }}:
          - template: support/download-release-notes.yml@rsg
      - template: support/install-dotnet.yml@rsg
        parameters:
          DotNetSdk:
            - '2.x'
            - '3.x'
          AuthNuGetFeeds:
            - name: RocketSurgeonsGuild
              source: https://nuget.pkg.github.com/RocketSurgeonsGuild/index.json
              username: $(GitHub.UserName)
              password: $(GitHub.Token)
      - template: support/gitversion-hack.yml@rsg

      - task: DotNetCoreCLI@2
        displayName: 'dotnet tool restore'
        inputs:
          command: custom
          custom: tool
          arguments: 'restore'

      - task: DotNetCoreCLI@2
        displayName: 'dotnet restore'
        inputs:
          command: restore
          feedsToUse: config
          nugetConfigPath: NuGet.config
          verbosityRestore: Minimal

      - template: ./azure-pipelines.nuke.yml
        parameters:
          Artifacts: $(Artifacts)
          Configuration: $(Configuration)
          Coverage: $(Coverage)

      - template: support/publish-artifacts.yml@rsg
        parameters:
          Artifacts: $(Artifacts)
          Configuration: $(Configuration)
          Coverage: $(Coverage)
          Postfix: ' - $(BuildName)'
          PublishVSTest: true
