trigger:
  branches:
    include:
      - master
      - feature/*
      - release/*
      - refs/tags/*
pr:
  autoCancel: true
  branches:
    include:
      - master

resources:
  repositories:
    - repository: rsg
      type: github
      name: RocketSurgeonsGuild/AzureDevopsTemplates
      ref: refs/tags/v0.11.3
      endpoint: github

variables:
  - group: rsg-bot
  - name: CONFIGURATION
    value: Release
  - name: VERBOSITY
    value: Normal
  - name: COVERAGE
    value: "$(Agent.BuildDirectory)/c"
  - name: ARTIFACTS
    value: $(Build.ArtifactStagingDirectory)
  - name: DOTNET_SKIP_FIRST_TIME_EXPERIENCE
    value: "true"
  - name: CodeCovToken
    value: 'abd8cf66-21fa-45eb-b45e-35a3022a7402'

jobs:
  - template: pipeline/nuke.yml@rsg
    parameters:
      AuthNuGetFeeds:
        - name: RocketSurgeonsGuild
          source: https://nuget.pkg.github.com/RocketSurgeonsGuild/index.json
          username: $(GitHub.UserName)
          password: $(GitHub.Token)
      Configuration: $(Configuration)
      Verbosity: $(Verbosity)
      GitHub: true
      GitHubAuthVariableGroup: rsg-bot
      GitHubPackages: false
      EnableReleaseNotes: false
      MyGetPackages: false
      DotNetSdk:
        - "2.x"
        - "3.x"
      NuGetVersion: "5.3.1"