trigger:
  branches:
    include:
      - master
      - feature/*
      - refs/tags/*
pr:
  autoCancel: true
  branches:
    include:
      - master

resources:
  repositories:
    - repository: rsg
      type: github
      name: RocketSurgeonsGuild/AzureDevopsTemplates
      ref: refs/tags/v0.8.5
      endpoint: github

variables:
  - group: rsg-bot
  - name: CONFIGURATION
    value: Release
  - name: VERBOSITY
    value: Normal
  - name: COVERAGE
    value: "$(Agent.BuildDirectory)/c"
  - name: ARTIFACTS
    value: $(Build.ArtifactStagingDirectory)
  - name: DOTNET_SKIP_FIRST_TIME_EXPERIENCE
    value: "true"
  - name: CodeCovToken
    value: 'ed1436a4-a776-4296-87e9-fe419e291c15'

jobs:
  - job: GitVersion
    pool:
      vmImage: "VS2017-Win2016"
    steps:
      - template: gitversion/store.yml@rsg
        parameters:
          NuGetVersion: "5.2.0"

  - template: pipeline/nuke-job.yml@rsg
    parameters:
      name: 'macOS'
      dependsOn: GitVersion
      vmImage: "macOS-10.14"
      Configuration: $(Configuration)
      Verbosity: $(Verbosity)
      DotNetVersion: "2.2.301"
      DotNet3Version: "3.0.100-preview7-012821"
      NuGetVersion: "5.2.0"
      
  - job: Publish
    pool:
      vmImage: "windows-2019"
    dependsOn:
      - macOS
    steps:
      - download: current
        artifact: 'Nupkg - macOS'
      - template: standard/nuget-push.yml@rsg
        parameters:
          Artifacts: "$(Pipeline.Workspace)/Nupkg - macOS/"
          NuGetVersion: "5.2.0"
          Verbosity: $(Verbosity)
          GitHubPackages: false